@startuml

note "适配器模式" as name
note "类适配器模式" as mode

interface Target{
    + {abstract} request()
}

class Adapter{
    + request()
}

class Adaptee {
    + specificRequest()
}

Target <|.. Adapter
Adapter --|> Adaptee

Client ..> Target


footer
<font size="20" color="red">http://www.bughui.com</font>
endfooter

@enduml