@startuml

note "简单工厂模式" as name

abstract class Product {
    + {abstract} operation()
}

class ProductA extends Product{
    + operation()
}

class ProductB extends Product{
    + operation()
}

class ProductC extends Product{
    + operation()
}


class Factory {
    + {static} Product getProduct()
}

Factory ..> Product : 创建

class Client{

}

Client ..> Factory

footer
<font size="20" color="red">http://www.bughui.com</font>
endfooter

@enduml