@startuml

note "外观模式" as name

interface Facade{
    + {abstract} operationX()
    + {abstract} operationY()
}

class ConcreteFacade{
    - moduleA: ModuleA
    - moduleB: ModuleB
    - moduleC: ModuleC
    + Facade()
    + operationX()
    + operationY()
}

class ModuleA{
    + operation1();
}

class ModuleB{
    + operation2();
}

class ModuleC{
    + operation3();
}

Facade <|.. ConcreteFacade
ConcreteFacade --> ModuleA
ConcreteFacade --> ModuleB
ConcreteFacade --> ModuleC

Client ..> Facade

note "内部模块/子系统" as n1

n1 .. ModuleA
n1 .. ModuleB
n1 .. ModuleC

footer
<font size="20" color="red">http://www.bughui.com</font>
endfooter

@enduml